version: "3"

services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    ports:
      - 53:53/tcp
      - 53:53/udp
      - 67:67/udp
      - 80:80/tcp
      - 443:443/tcp
    environment:
      TZ: America/New_York
      WEBPASSWORD: "${WEBPASSWORD}"
      ServerIP: 192.168.1.31
      DNS1: 1.1.1.1
      DNS2: 1.0.0.1
      DNSSEC: "true"
      DNS_BOGUS_PRIV: "true"
      DNS_FQDN_REQUIRED: "true"
      REV_SERVER: "true"
      REV_SERVER_CIDR: 192.168.0.0/16
      REV_SERVER_TARGET: 192.168.1.1
    volumes:
      - ./hosts:/etc/hosts
      - ./etc-pihole/:/etc/pihole/
      - ./etc-dnsmasq.d/:/etc/dnsmasq.d/
    cap_add:
      - NET_ADMIN
    env_file:
      - .env
    dns:
      - 127.0.0.1
      - 1.1.1.1
    restart: unless-stopped
