- hosts: all
  become: yes

  pre_tasks:
    - name: Update and upgrade apt packages
      apt:
        upgrade: "yes"
        update_cache: yes
        cache_valid_time: 3600
    - name: Install zsh
      apt:
        name: zsh

  roles:
    - role: viasite-ansible.zsh
      zsh_aliases:
        - alias: python
          action: python3
        - alias: rmd
          action: rm -rf
        - alias: c
          action: clear
      zsh_antigen_bundles:
        - git
        - last-working-dir
        - history
        - z
        - zsh-users/zsh-syntax-highlighting
        - zsh-users/zsh-autosuggestions
        - unixorn/autoupdate-antigen.zshplugin

    - role: geerlingguy.pip
      pip_package: python3-pip

    - role: geerlingguy.docker_arm

    - role: ansible-role-nvm
      nodejs_version: "14.5.0"
      nvm_profile: "$HOME/.zshrc"
      tags: [nodejs]

    - role: ocha.yarn
      tags: [nodejs]

  tasks:
    - name: Set authorized key
      ansible.posix.authorized_key:
        user: root
        state: present
        key: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"
      tags: [ssh]

    - name: Enable root login over SSH
      lineinfile:
        dest: /etc/ssh/sshd_config
        regexp: "^PermitRootLogin"
        line: "PermitRootLogin yes"
        state: present
      tags: [ssh]

    - name: Disable SSH authentication with password
      lineinfile:
        dest: /etc/ssh/sshd_config
        regexp: "^PasswordAuthentication"
        line: "PasswordAuthentication no"
        state: present
      tags: [ssh]

    - name: Set static IP address
      blockinfile:
        path: /etc/dhcpcd.conf
        block: "{{ lookup('file', './files/dhcpcd.conf') }}"
        insertbefore: EOF
      tags: [network]

  post_tasks:
    - name: Stop and start ssh
      service:
        name: ssh
        state: restarted
    - name: Stop and start dhcpcd
      service:
        name: dhcpcd
        state: restarted
    - name: Reload zsh
      command: "/bin/zsh -c 'source ~/.zshrc'"


